spring:
  velocity:
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/smzdm?serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 80

